data_path : ""           # path to folder containing noisy images
max_epoch : 3000         # training epochs per image
lr : 0.001               # learning rate
step_size : 1000         # number of epochs at which learning rate decays
gamma : 0.5              # factor by which learning rate decays
